# docker-compose file
# basically this file define all the services that make up the application

version: '3.7'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todolist_dbuser
      - POSTGRES_PASSWORD=todolist_dbpassword
      - POSTGRES_DB=todolist_dev_db

volumes:
  postgres_data: